In [1]:
import numpy as np
# import numpy as random
from numpy import random

In [2]:
# Create and inspect Arrays
first = np.arange(1,10)
second = first.reshape((3,3))
print(second)
second.shape
second.size

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

In [3]:
# Indexing and slicing
third = np.arange(1,17)
fourth = third.reshape((4,4))

first_value = np.flip(fourth[0])
second_value = fourth[2]
third_value = fourth[3]

In [4]:
# Array Operation
fifth = np.arange(0,5)
sixth = np.nditer(fifth)
res_map = map(lambda a: a + 5 ,np.array(sixth))
last_res_map = np.array(list(res_map)) 
last_res_map_2 = np.multiply(last_res_map, 3) 
np.sum(last_res_map_2).item()

105

In [5]:
# Statistical function
seventh = np.arange(10, 60, 10)
np.mean(seventh).item()
np.max(seventh).item()
np.min(seventh).item()
np.sum(seventh).item()


150

In [6]:
# Reshape Arrays
eighth = np.arange(1,13)
print(eighth)
res_value = eighth.reshape((3,4))
print(res_value)
res_value_2 = res_value.flatten()
print(res_value_2)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
# Create Arrays with Special Values

np.zeros((4,4))
np.ones((3,5))
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# Random Arrays

np.random.rand(5)
np.random.randint(1,100, (3,3))


array([[16, 98, 33],
       [46, 66,  5],
       [18, 73, 45]])

In [9]:
# Boolean Indexing

# np.random.randint(1,15,(1,5))
# np.arange(6)
nineth = np.linspace(3, 16, num=6)
tenth = nineth[nineth > 9] = 0
print(nineth)


[3.  5.6 8.2 0.  0.  0. ]


In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

arr2 = np.array((6,7,8,9,10))
print(arr2)

# 0D
arr3 = np.array(42)
print("0D")
print(arr3)
# print(type(arr3))
print(arr3.ndim)

# 1D
arr4 = np.array([1, 2, 3, 4, 5])
print("1D")
print(arr4)
# print(type(arr4))
print(arr4.ndim)

# 2D
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D")
print(arr5)
# print(type(arr5))
print(arr5.ndim)

# 3D
arr6 = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])
print("3D")
print(arr6)
# print(type(arr6))
print(arr6.ndim)


arr7 = np.array([1,2,3,4,5], ndmin=5)
print(arr7)
# print(type(arr6))
print(arr7.ndim)


[1 2 3 4 5]
[ 6  7  8  9 10]
0D
42
0
1D
[1 2 3 4 5]
1
2D
[[1 2 3]
 [4 5 6]]
2
3D
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
[[[[[1 2 3 4 5]]]]]
5


In [11]:
# Slicing 
arr8 = np.array([1, 2, 3, 4, 5, 6])
print(arr8[1:3])
print(arr8[2:])
print(arr8[-4:-1])
print(arr8[1:5:2])

[2 3]
[3 4 5 6]
[3 4 5]
[2 4]


In [12]:
# DataType
arr9 = np.array([1, 2, 3, 4, 5, 6])
print(arr9.dtype)



int64


In [13]:
# copy and view

arr10 = np.array([1, 2, 3, 4, 5, 6])
x = arr10.copy()
print(x)
arr10[0] = 50
print(arr10)

[1 2 3 4 5 6]
[50  2  3  4  5  6]


In [14]:
# shape of array

arr11 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr11.shape)

(2, 4)


In [15]:
# Join array

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [16]:
# Searching 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# x = np.where(arr == 4)
# print(x)

y = np.where(arr % 2 == 1)
print(y)

(array([0, 2, 4, 6]),)


In [17]:
# Sort
arr = np.array([3, 2, 0, 1])

arr = np.array(['banana', 'cherry', 'apple'])

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [18]:
# Filtering

arr = np.array([41, 42, 43, 44])

new_arr = []
for i in arr:
    # print(i)
    if i > 42:
        new_arr.append(True)
    else : 
        new_arr.append(False)

# print(new_arr)
new_arr_2 =  arr[new_arr]
print(new_arr_2)

[43 44]


In [19]:
# Random number

x = np.random.randint(100)
y = np.random.randint(100, size=5)
z = np.random.rand(3, 5)

x1 = np.random.choice([3, 5, 7, 9])
x2 = np.random.choice([3, 5, 7, 9], size=(3, 5))

x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

# print(x)
# print(x2)

[[7 5 7 7 7]
 [7 7 7 7 7]
 [7 5 7 7 7]]


In [20]:
# Random Permutations

arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)

print(arr)
print(np.random.permutation(arr))

[5 1 4 2 3]
[1 5 2 3 4]


In [21]:
# Normal (Gaussian) Distribution
# x = np.random.normal(size=(2, 3))
x = np.random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[ 2.22813983  3.74329251  0.95308246]
 [ 1.23587148 -3.54790172 -0.47013627]]


In [22]:
# Random Arrays
gen = np.random.randint(2, size=5)
print(gen)

gen2 = np.random.randint(100, size=(3,3))
print(gen2)

[0 1 0 0 1]
[[44 92 63]
 [79 40 88]
 [60 22 92]]


In [23]:
# Boolean Indexing

arr = np.array([3, 6, 9, 12, 15])

fil_arr = arr > 9
print(arr[fil_arr])

new_arr = []
for i in arr:
    if i > 10:
        new_arr.append(i)
    else: 
        new_arr.append(10)

print(arr)
# print(new_arr)
x = np.array(new_arr)
print(x)

[12 15]
[ 3  6  9 12 15]
[10 10 10 12 15]


In [24]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)

print(b)

In [25]:
# BroadCasting
matrix = np.random.randint(20, size=(3,3))
one_D = np.random.randint(10, size=3)
print(matrix)
print(one_D)

last = matrix + one_D
print(last)


array1 = np.ones((2, 3, 4))
array2 = np.arange(4)
                        
# Adding arrays with broadcasting
result = array1 + array2
print(result)

[[19 17 12]
 [19 14 10]
 [19  2  6]]
[7 1 1]
[[26 18 13]
 [26 15 11]
 [26  3  7]]
[[[1. 2. 3. 4.]
  [1. 2. 3. 4.]
  [1. 2. 3. 4.]]

 [[1. 2. 3. 4.]
  [1. 2. 3. 4.]
  [1. 2. 3. 4.]]]


In [26]:
# Matrix Operations

satu = np.random.randint(10, size=(2,2))
dua = np.random.randint(5, size=(2,2))

print(satu)
print(dua)

kali = satu * dua
print(kali)

tambah = satu + dua
print(tambah)

[[1 5]
 [7 7]]
[[2 1]
 [2 3]]
[[ 2  5]
 [14 21]]
[[ 3  6]
 [ 9 10]]


In [27]:
# Sorting

arr = np.random.randint(10, size=(10))
arr2 = np.sort(arr)
print(arr)
print(arr2)

arr = np.random.randint(10, size=(5,5))
arr2 = np.sort(arr)

print(arr)
print(arr2)

[7 9 4 2 0 6 0 0 2 0]
[0 0 0 0 2 2 4 6 7 9]
[[0 3 6 1 6]
 [8 4 4 0 3]
 [5 2 1 1 4]
 [5 3 1 8 9]
 [5 8 8 5 2]]
[[0 1 3 6 6]
 [0 3 4 4 8]
 [1 1 2 4 5]
 [1 3 5 8 9]
 [2 5 5 8 8]]


In [28]:
# Use np.linspace and np.arange

satu = np.linspace(0, 5, 10)
print(satu)

dua =  np.arange(10, 100, 10)
print(dua)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[10 20 30 40 50 60 70 80 90]


In [29]:
# NumPy - Array Creation Routines

arr = np.array([1,2,3,4,5])

arr = np.zeros(5)

arr = np.ones(5)

arr = np.ones((4,3))

arr = np.ones((4,3), order='F')

arr = np.arange(1, 10, 2)

arr = np.linspace(0, 5, num=10)

arr = np.random.rand(5, 5)

arr = np.empty((2,3))

arr = np.full((2,3),2)

my_bytes = b'Hello world!'
print(my_bytes)
print(arr)

b'Hello world!'
[[2 2 2]
 [2 2 2]]


In [30]:
# NumPy - Array From Numerical Ranges

arr = np.arange(1, 10)

arr = np.linspace(1, 10)

arr = np.logspace(1, 10, 10, base=2)

x = np.arange(1,4)
y = np.arange(1,3)

# print(x)
# print(y)

X,Y = np.meshgrid(x,y)

print(X)
print(Y)


[[1 2 3]
 [1 2 3]]
[[1 1 1]
 [2 2 2]]


In [31]:
# Exercise 1

arr = np.arange(10)
arr = np.random.randint(1, 9, size=(3,3))
print(arr)

[[2 6 1]
 [5 8 1]
 [1 2 2]]


In [32]:
# Exercise 2

arr = [5, 10, 15, 20, 25]
arr = np.array(arr)
shape_arr = arr.shape
dim_arr = arr.ndim
size_arr = arr.size


print(shape_arr)
print(dim_arr)
print(size_arr)


(5,)
1
5


In [33]:
# Exercise 3

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

size_arr = arr.size

ext_arr = arr[1,1]
sec_arr = arr[2]
last_arr = arr[:,2]
print(ext_arr)
print(sec_arr)
print(last_arr)


5
[7 8 9]
[3 6 9]


In [34]:
# Exercise 4

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b
print(result)

result2 = a * 2
print(result2)


result3 = np.dot(a, b)
print(result3)

[5 7 9]
[2 4 6]
32


In [35]:
# Exercise 5

c = np.zeros((4,4))
print(c)

d = np.ones((3,3))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
# Exercise 6 (case)

temperatures = np.array([22.5, 23.0, 19.8, 21.7, 20.5, 18.9, 22.0])

def count(c):
    res = (c * 9/5) + 32
    return res

hasil = count(temperatures)
avg = np.mean(temperatures)
avg2 = np.mean(hasil)
identify = np.where(temperatures > 21, 'Hot', temperatures)

print(hasil)
print(avg)
print(avg2)
print(identify)


[72.5  73.4  67.64 71.06 68.9  66.02 71.6 ]
21.2
70.16
['Hot' 'Hot' '19.8' 'Hot' '20.5' '18.9' 'Hot']


In [37]:
# Exercise 7 (case)


prices = np.array([150.25, 152.35, 149.90, 153.40, 151.80])


old_prices = prices[:-1]
new_price = prices[1:]

percentage = (new_price - old_prices) / old_prices * 100

prices_max = np.max(prices)
prices_min = np.min(prices)

percentage_max = np.max(percentage)
idx_percentage_max = np.searchsorted(percentage, percentage_max)

print(old_prices)
print(new_price)
print(percentage)
print(f"Max {prices_max} and Min {prices_min}")
print(f"{percentage_max}, with idx {idx_percentage_max}")

[150.25 152.35 149.9  153.4 ]
[152.35 149.9  153.4  151.8 ]
[ 1.39767055 -1.60813915  2.33488993 -1.04302477]
Max 153.4 and Min 149.9
2.334889926617745, with idx 2


In [38]:
# Exercise 8 (case)

spending = np.array([45.50, 67.80, 120.00, 35.75, 98.50, 150.20, 65.90])

sum = np.sum(spending)
avg = np.mean(spending)
print(sum)
print(avg)
find = spending > avg
res = spending[find]
idx = np.where(np.isin(spending, res))[0]


print(spending)
print(res)
print(idx)


583.65
83.37857142857142
[ 45.5   67.8  120.    35.75  98.5  150.2   65.9 ]
[120.   98.5 150.2]
[2 4 5]


In [47]:
# Exercise 9 (case)

image = np.array([[100, 150, 200],
                  [50, 75, 125],
                  [0, 25, 50]])

icr = np.where((image + 50) > 255, 255, (image + 50))
print(icr)

idx = np.where(image > 100)
print(idx)
val_idx = image[idx]
print(val_idx)

replace = np.where(image < 50, 0, image)
print(replace)



[[150 200 250]
 [100 125 175]
 [ 50  75 100]]
(array([0, 0, 1]), array([1, 2, 2]))
[150 200 125]
[[100 150 200]
 [ 50  75 125]
 [  0   0  50]]


In [61]:
# Exercise 10 (case)

sales = np.array([[2500, 3000, 4000, 3500],  # Year 1
                  [2800, 3200, 4100, 3700]]) # Year 2

sum = np.sum(sales, axis=1)
avg = np.mean(sales, axis=0)
avg1 = np.mean(sales, axis=1)
highest_max = np.argmax(sales, axis=1)
print(sum)
print(avg)
print(avg1)
print(highest_max)


[13000 13800]
[2650. 3100. 4050. 3600.]
[3250. 3450.]
[3 3]


In [72]:
# Exercise 11 (case)

ages = np.random.randint(18, 66, size=100)

print(ages)

age_mean = np.mean(ages)
print(age_mean)

param = (ages >= 18) & (ages <= 30)
param2 = (ages >= 31) & (ages <= 50)
param3 = (ages >= 51) & (ages <= 65)
val = np.count_nonzero(param)
val2 = np.count_nonzero(param2)
val3 = np.count_nonzero(param3)
print(val)
print(val2)
print(val3)

[28 32 50 24 49 33 24 56 40 23 58 44 27 32 35 40 20 24 39 35 53 39 36 54
 59 53 63 33 48 32 58 42 19 42 31 22 60 41 27 25 49 41 24 43 48 28 47 20
 24 61 29 35 32 52 59 64 34 34 45 60 25 41 21 24 21 65 59 35 42 20 37 51
 18 54 57 39 35 35 31 56 50 28 47 44 39 50 59 57 65 42 40 22 23 42 44 43
 51 53 49 35]
40.28
25
50
25


In [76]:
# Exercise 12 (case)

rainfall = np.array([[12.3, 15.2, 8.7],
                     [10.5, 13.1, 9.8],
                     [14.6, 17.3, 12.0],
                     [9.8, 11.2, 6.4],
                     [13.2, 16.4, 10.1],
                     [11.7, 14.9, 8.9],
                     [8.9, 12.5, 7.3]])

avg = np.sum(rainfall, axis=0)
max = np.max(rainfall, axis=0)
least = rainfall[-1]
print(avg)
print(max)
print(least)


[ 81.  100.6  63.2]
[14.6 17.3 12. ]
[ 8.9 12.5  7.3]


In [86]:
# Exercise 13 (case)

scores = np.array([[12, 18, 20],
                   [25, 22, 30],
                   [15, 19, 17],
                   [10, 12, 15],
                   [28, 25, 27]])

calculate = np.sum(scores, axis=1)
max = np.max(calculate)
find = np.where(calculate == max)[0]
highest_max = np.max(scores, axis=0) 
print(calculate)
print(f"Max value {max} at index {find}")
print(highest_max)

[50 77 51 37 80]
Max value 80 at index [4]
[28 25 30]


In [90]:
# Exercise 14 (case)

loan_amounts = np.array([10, 15, 20, 25, 30])
interest_rates = np.array([5.0, 4.5, 4.0, 3.5, 3.0])

val = loan_amounts * (interest_rates / 100)
print(val)
sum_val = np.sum(val)
print(sum_val)
max_val = np.max(val)
print(max_val)

[0.5   0.675 0.8   0.875 0.9  ]
3.75
0.8999999999999999


In [101]:
# Exercise 15 (case)
salaries = np.array([[3000, 3200, 3100],  # Department 1
                     [4500, 4300, 4200],  # Department 2
                     [5000, 5200, 5100]]) # Department 3


calculate = np.sum(salaries, axis=1)
max_payment = np.max(salaries, axis=0)
print(calculate)
print(max_payment)
avg_payment = np.mean(salaries)
print(avg_payment)

[ 9300 13000 15300]
[5000 5200 5100]
4177.777777777777
