In [30]:
import numpy as np
from numpy.random import default_rng

# Array Creation


---

`inisial with npm init --y`


<img src="https://imgs.search.brave.com/et-V10zzizp8cArlR5zOwy-Rs-lrMecpRnk08B-3dj4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9yYXcu/Z2l0aHVidXNlcmNv/bnRlbnQuY29tL1Ro/ZUR1ZGVUaGF0Q29k/ZS9UaGVEdWRlVGhh/dENvZGUvbWFzdGVy/L0Fzc2V0cy9EZXZl/bG9wZXIuZ2lm.jpeg" />

In [31]:
a1d = np.array([1,2,3,4])
a2d = np.array([[1,2],[2,3]])
# print(a2d)
a23 = np.array([[1,2],[2,3],[4,5]])

In [32]:
np.arange(10)
np.arange(10, dtype=float)
np.linspace(1, 5, 3)
np.arange(1, 20, 5)

array([ 1,  6, 11, 16])

In [33]:
np.eye(3)
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [34]:
np.diag([1,2,3,])
np.diag([1,2,3],1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [35]:
np.vander([1,2,3,4])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [36]:
np.zeros((2,3,2))
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [38]:
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [39]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [43]:
a = np.array([1,2,3,4,5,6])
b = a[:2]
print(b)
b += 1
print(b)

[1 2]
[2 3]


In [47]:
np.random.rand(10,2)

array([[0.42795324, 0.98497125],
       [0.04307523, 0.28644899],
       [0.11818453, 0.70228748],
       [0.53025392, 0.08333434],
       [0.66458387, 0.49197293],
       [0.23085096, 0.21248339],
       [0.15584022, 0.07905613],
       [0.53909472, 0.16150811],
       [0.27925658, 0.00981255],
       [0.87176106, 0.53105776]])

In [48]:
np.random.randn(10)

array([-1.46322979, -0.70082685,  0.65449487,  0.03967852, -1.40637748,
       -0.24746035,  0.40786597,  0.36318084, -0.95470273, -2.1368425 ])

In [50]:
my_list = [1,2,3]
arr_id = np.array(my_list)

arr_id.shape

(3,)

In [51]:
my_list2 = [[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]

arr_id2 = np.array(my_list2)
arr_id2.shape

(3, 3)

In [64]:
my_list3 =np.arange(25)

my_list3.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
my_list4 = [[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]]

arr_id4 = np.array(my_list4)
arr_id4.max()
arr_id4.min()
arr_id4.argmax()
arr_id4.argmin()
arr_id4.dtype

dtype('int64')